@startuml
class CameraBounds {
    Start() : void
    LateUpdate() : void
    UpdateCanvasBounds() : void
    ClampCameraPosition() : void
    + SetZoom(newSize:float) : void
}
MonoBehaviour <|-- CameraBounds
CameraBounds --> "mainCamera" Camera
CameraBounds --> "canvasRect" RectTransform
@enduml
