@startuml
class Adjective {
    + Base : string <<get>> <<set>>
    + SingularNominativeFeminine : string <<get>> <<set>>
    + SingularGenitiveFeminine : string <<get>> <<set>>
    + SingularNominativeMasculine : string <<get>> <<set>>
    + SingularNominativeNeuter : string <<get>> <<set>>
    + SingularGenitiveOther : string <<get>> <<set>>
    + PluralNominative : string <<get>> <<set>>
    + PluralGenitive : string <<get>> <<set>>
    + Adjective(Base:string, SingularNominativeFeminine:string, SingularGenitiveFeminine:string, SingularNominativeMasculine:string, SingularNominativeNeuter:string, SingularGenitiveOther:string, PluralNominative:string, PluralGenitive:string)
    + {static} ToAdjective(values:object[]) : Adjective
    + SingNomFem(Title:int) : string
    + SingNomMasc(Title:int) : string
    + SingNomNeuter(Title:int) : string
    + SingGenFem(Title:int) : string
    + SingGenOther(Title:int) : string
    + PluralNom(Title:int) : string
    + PluralGen(Title:int) : string
}
DbClass <|-- Adjective
@enduml
