@startuml
class Hazard {
    + id : int <<get>> <<set>>
    + Name : string <<get>> <<set>>
    + Complexity : string <<get>> <<set>>
    + Description : string <<get>> <<set>>
    + MechDescription : string <<get>> <<set>>
    + Level : int <<get>> <<set>>
    + Stealth : string <<get>> <<set>>
    + Hazard()
    + Hazard(id:int, name:string, complexity:string, description:string, mechDescription:string, level:int, stealth:string)
    + {static} ToHazard(values:object[]) : Hazard
    + <<override>> ToString() : string
    + ToTextFileString() : string
}
DbClass <|-- Hazard
@enduml
