@startuml
class Monster {
    + id : int <<get>> <<set>>
    + Name : string <<get>> <<set>>
    + Description : string <<get>> <<set>>
    + MechDescription : string <<get>> <<set>>
    + Level : int <<get>> <<set>>
    + Monster()
    + Monster(id:int, Name:string, Description:string, MechDescription:string, Level:int)
    + {static} ToMonster(values:object[]) : Monster
    + <<override>> ToString() : string
    + ToTextFileString() : string
}
DbClass <|-- Monster
@enduml
