@startuml
class Name {
    + Base : string <<get>> <<set>>
    + SingularNominative : string <<get>> <<set>>
    + SingularGenitive : string <<get>> <<set>>
    + PluralNominative : string <<get>> <<set>>
    + PluralGenitive : string <<get>> <<set>>
    + Name(Base:string, SingularNominative:string, SingularGenitive:string, PluralNominative:string, PluralGenitive:string, gender:Gender)
    + {static} ToName(values:object[]) : Name
    + SingNom() : string
    + SingGen() : string
    + PluralNom() : string
    + PluralGen() : string
}
DbClass <|-- Name
Name --> "Gender" Gender
@enduml
