@startuml
class Noun {
    + Base : string <<get>> <<set>>
    + SingularNominative : string <<get>> <<set>>
    + SingularGenitive : string <<get>> <<set>>
    + PluralNominative : string <<get>> <<set>>
    + PluralGenitive : string <<get>> <<set>>
    + Title : int <<get>> <<set>>
    + Noun(Base:string, SingularNominative:string, SingularGenitive:string, PluralNominative:string, PluralGenitive:string, gender:Gender, title:int)
    + {static} ToNoun(values:object[]) : Noun
    + SingNom() : string
    + SingGen() : string
    + PluralNom() : string
    + PluralGen() : string
}
DbClass <|-- Noun
Noun --> "Gender" Gender
@enduml
