@startuml
class DBManager {
    {static} dbName : string = "/DungeonGenerator.db"
    + {static} dbLink : string
    + useHumansInBattle : bool = true
    + useHazards : bool = true
    Awake() : void
    InitGenerators() : void
    {static} CheckDB() : bool
    + GenerateRoomsContent(partyMemberAmount:int, partyLevel:int, roomAmount:int, useHumansInBattle:bool, useHazards:bool) : List<Tuple<int, List<Monster>, List<Hazard>>>
    + GenerateRoomsContent(partyMemberAmount:int, partyLevel:int, roomCoordinates:List<object>, useHumansInBattle:bool, useHazards:bool) : List<Tuple<object, List<Monster>, List<Hazard>>>
    + SaveRoomContentsToFile(rooms:List<Tuple<object, List<Monster>, List<Hazard>>>) : void
    generateDungeonName() : String
}
MonoBehaviour <|-- DBManager
@enduml
