@startuml
class HazardGenerator {
    + HazardGenerator()
    + BuildHazard(xpbudget:int, party_level:int) : List<Hazard>
    + BuildSimpleHazard(xpbudget:int, party_level:int) : int
}
class "Dictionary`2"<T1,T2> {
}
ObjectGenerator <|-- HazardGenerator
HazardGenerator o-> "simpleExpCostList<int,int>" "Dictionary`2"
HazardGenerator o-> "complexExpCostList<int,int>" "Dictionary`2"
HazardGenerator o-> "simple_hazards_by_lvl<int,List<Hazard>>" "Dictionary`2"
HazardGenerator o-> "complex_hazards_by_lvl<int,List<Hazard>>" "Dictionary`2"
HazardGenerator --> "hazard" Hazard
@enduml
