@startuml
class MonsterGenerator {
    + MonsterGenerator()
    + useHumansInBattle : bool
    + BuildCombat(xpbudget:int, party_level:int, _useHumansInBattle:bool) : List<Monster>
}
class "Dictionary`2"<T1,T2> {
}
ObjectGenerator <|-- MonsterGenerator
MonsterGenerator --> "monster" Monster
MonsterGenerator o-> "expcostlist<int,int>" "Dictionary`2"
MonsterGenerator o-> "monsters_by_lvl<int,List<Monster>>" "Dictionary`2"
@enduml
