@startuml
class NameGenerator {
    nameRowsCount : int = 0
    nounRowsCount : int = 0
    adjRowsCount : int = 0
    result : string = ""
    temp_word : string = ""
    + NameGenerator()
    + GenerateName() : string
}
class "List`1"<T> {
}
ObjectGenerator <|-- NameGenerator
NameGenerator o-> "found_name" Name
NameGenerator o-> "found_noun" Noun
NameGenerator o-> "found_adjective" Adjective
NameGenerator --> "gender" Gender
NameGenerator o-> "names<Name>" "List`1"
NameGenerator o-> "nouns<Noun>" "List`1"
NameGenerator o-> "adjectives<Adjective>" "List`1"
@enduml
