@startuml
class ThreatGenerator {
    + ThreatGenerator()
    + BuildEncounter(party_member_amount:int, party_level:int, room_amount:int, useHumansInBattle:bool, useHazards:bool) : List<Tuple<int, List<Monster>, List<Hazard>>>
    + BuildEncounter(party_member_amount:int, party_level:int, roomsCoordinates:List<object>, useHumansInBattle:bool, useHazards:bool) : List<Tuple<object, List<Monster>, List<Hazard>>>
    + RandomDifficulty(random:System.Random) : string
    + BuildRoom(difficulty:string, useHumansInBattle:bool, useHazards:bool) : void
}
class "Dictionary`2"<T1,T2> {
}
ObjectGenerator <|-- ThreatGenerator
ThreatGenerator o-> "xb_by_difficulty<string,int>" "Dictionary`2"
ThreatGenerator o-> "xp_by_party_size<string,int>" "Dictionary`2"
@enduml
