@startuml
class DungeonGenerator {
    + roomCount : int = 10
    + minRoomSeparation : float = 3f
    + {static}  <<event>> OnGeneration : Generation 
    Start() : void
    + RegenerateDungeon() : void
    ClearDungeon() : void
    GenerationRoutine() : void
    PlaceRooms() : void
    SeparateRooms() : void
    ConnectRooms() : void
    CreateRoom(room:Room) : void
    CreateCorridor(roomA:Room, roomB:Room) : void
    CreateCorridorSegment(start:Vector2, end:Vector2) : void
}
MonoBehaviour <|-- DungeonGenerator
DungeonGenerator o-> "minRoomSize" Vector2
DungeonGenerator o-> "maxRoomSize" Vector2
DungeonGenerator o-> "dungeonSize" Vector2
@enduml
