@startuml
class TilemapEditor {
    + isEditingMode : bool = false
    Update() : void
    + ToggleEditingMode() : void
}
MonoBehaviour <|-- TilemapEditor
TilemapEditor --> "tilemap" Tilemap
TilemapEditor --> "floorTile" RuleTile
TilemapEditor --> "wallTile" RuleTile
@enduml
